; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:frdm_kl25z]
platform = freescalekinetis
board = frdm_kl25z
framework = zephyr
platform_packages =
    platformio/framework-zephyr@~3.40200.0
    toolchain-gccarmnoneeabi@~1.90301.0
    tool-openocd

debug_tool = custom
debug_server = 
  ${platformio.packages_dir}/tool-openocd/bin/openocd
  -f
  interface/cmsis-dap.cfg
  -f
  target/kl25.cfg

